### ISSUE TITLE
Progression of errors while installing

### ISSUE THREAD

**Issue by santiagodemierre** [alirezamika/autoscraper#1]
### 1

santiago@santiago-Aspire-A515-51:~$ pip install git+https://github.com/alirezamika/autoscraper.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/alirezamika/autoscraper.git
  Cloning https://github.com/alirezamika/autoscraper.git to /tmp/pip-req-build-zjd5pn9g
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zjd5pn9g/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zjd5pn9g/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-du5i409j
         cwd: /tmp/pip-req-build-zjd5pn9g/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zjd5pn9g/setup.py", line 7, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-zjd5pn9g/README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### 2 - Git clone manually, installed setuptools manually, then Readme.rst not found

santiago@santiago-Aspire-A515-51:~/Devel/autoscraper$ python3.8 -m pip install setuptools
Collecting setuptools
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/b0/8b/379494d7dbd3854aa7b85b216cb0af54edcb7fce7d086ba3e35522a713cf/setuptools-50.0.0-py3-none-any.whl (783kB)
    100% |████████████████████████████████| 788kB 615kB/s 
Installing collected packages: setuptools
Successfully installed setuptools-50.0.0
santiago@santiago-Aspire-A515-51:~/Devel/autoscraper$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
  File "/usr/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/santiago/Devel/autoscraper/README.rst'

### 3 - Renamed Readme.md to README.rst

santiago@santiago-Aspire-A515-51:~/Devel/autoscraper$ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.8/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

**Comment by alirezamika** [comment]
Can you try with sudo?
`sudo pip install git+https://github.com/alirezamika/autoscraper.git`

**Comment by santiagodemierre** [comment]
I tried again without sudo (before seeing your message)
Note python3.6 instead of 3.8 (my default) and note 'AustoScraper' instead of AutoScraper

Here's what I got 

santiago@santiago-Aspire-A515-51:~/Devel/autoscraper/autoscraper$ pip install git+https://github.com/alirezamika/autoscraper.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/alirezamika/autoscraper.git
  Cloning https://github.com/alirezamika/autoscraper.git to /tmp/pip-req-build-322ekajn
Requirement already satisfied: requests in /home/santiago/.local/lib/python3.6/site-packages (from autoscraper==1.0.0) (2.24.0)
Requirement already satisfied: bs4 in /home/santiago/.local/lib/python3.6/site-packages (from autoscraper==1.0.0) (0.0.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->autoscraper==1.0.0) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->autoscraper==1.0.0) (2018.1.18)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->autoscraper==1.0.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->autoscraper==1.0.0) (1.22)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->autoscraper==1.0.0) (4.6.0)
Building wheels for collected packages: autoscraper
  Building wheel for autoscraper (setup.py) ... done
  Created wheel for autoscraper: filename=autoscraper-1.0.0-py3-none-any.whl size=6651 sha256=a2853cc1db631247f2da7d888703dd5123833d68f44ee543dd13eb19bee9769b
  Stored in directory: /tmp/pip-ephem-wheel-cache-0xey7kc4/wheels/f5/d2/dd/1c9ee0e730efe6989ba7623a4e751552149d3fe3d1d63ae666
Successfully built autoscraper
Installing collected packages: autoscraper
Successfully installed autoscraper-1.0.0
santiago@santiago-Aspire-A515-51:~/Devel/autoscraper/autoscraper$ python
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autoscraper import AustoScraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'autoscraper'
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
santiago@santiago-Aspire-A515-51:~/Devel/autoscraper/autoscraper$ python3.6
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autoscraper import AustoScraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name **'AustoScraper'**

**Comment by santiagodemierre** [comment]
Dude that was dumb of me!!!

When you actually spell the module right it works
