### ISSUE TITLE
It is unable to scrape <li>

### ISSUE THREAD

**Issue by amztc34283** [alirezamika/autoscraper#100]
<img width="596" alt="Screenshot 2024-10-07 at 8 40 01 PM" src="https://github.com/user-attachments/assets/43614159-4397-44a2-8c4b-01aa7c0d9429">

```python
wanted_list = ["Design, develop, test, refactor and scale backend implementations of new and existing consumer product features"]

scraper = AutoScraper()
result = scraper.build(url, wanted_list)
```

I am able to scrape the element in the wanted_list but similar elements are not scraped successfully, any tips and tricks could fix this?

**Comment by alirezamika** [comment]
please provide your full code including the url.

**Comment by amztc34283** [comment]
```python
wanted_list = ["Design, develop, test, refactor and scale backend implementations of new and existing consumer product features"]
scraper = AutoScraper()
result = scraper.build(url, wanted_list)
print(result)
```

Link: https://careers.chime.com/en/jobs/4225356002/backend-engineer/

**Comment by alirezamika** [comment]
What is your expected output?

**Comment by amztc34283** [comment]
My expected output is the content of all the <li> under the same <ul>.

**Comment by alirezamika** [comment]
you can try the `contain_sibling_leaves` attribute.

`result = scraper.get_result_similar(url, contain_sibling_leaves=True)`

**Comment by amztc34283** [comment]
I will give it a try, thanks.

In addition, can you point me to the part of the code that decides which elements to scrape based on the wanted_list? Thank you!

**Comment by alirezamika** [comment]
its basically the whole code 😅
