### ISSUE TITLE
URL cannot carry parameters  

### ISSUE THREAD

**Issue by beichen2023** [alirezamika/autoscraper#101]
I have discovered a fatal issue
If the URL contains parameters, information cannot be obtained normally
Successful code
from autoscraper import AutoScraper
url = ' https://book.douban.com/ '
wanted_list = ["8.3"]
scraper = AutoScraper()
# Here we can also pass html content via the html parameter instead of the url (html=html_content)
result = scraper.build(url, wanted_list)
print(result)
Failed code  (?subcat=)
from autoscraper import AutoScraper
url = ' https://book.douban.com/latest?subcat=%E5%85%A8%E9%83%A8 '
wanted_list = ["67"]
scraper = AutoScraper()
# Here we can also pass html content via the html parameter instead of the url (html=html_content)
result = scraper.build(url, wanted_list)
print(result)

**Comment by alirezamika** [comment]
because the content is different and as i checked manually there's no 8.3 in the second url.

**Comment by alirezamika** [comment]
As i checked manually there's no 67 in the second url page. i checked with other wanted elements and there was no problem.
