### ISSUE TITLE
Add support for incremental learning 

### ISSUE THREAD

**Issue by Narasimha1997** [alirezamika/autoscraper#18]
As of now, the rules are formed at once based on the targets specified in `wanted_list` and the stack list is generated for those targets. Sometimes there will be scenarios where I have to update the existing stack list with new rules learnt from different set of targets on the same URL. As seen in the `build` method, you create a new stack list every time a build method is called. Provide an `update` method, that updates the stack list simply by appending the new rules learnt from new set of targets. 
This will be very useful functionality because it will allow developers to incrementally add new targets by retaining the older rules.

**Comment by alirezamika** [comment]
Sounds like a good idea. I think it can also be from different urls. Suppose you want to build a price scraper, you can feed it with samples of different websites, like amazon, ebay, etc.

**Comment by Narasimha1997** [comment]
Yes! that would be good. This will be like a Scraping marketplace. Learn rules -> Increment the learning (add more rules from different sources) -> Publish the rules so others can consume it.

**Comment by alirezamika** [comment]
Awesome!

**Comment by alirezamika** [comment]
#19
