### ISSUE TITLE
bs4.FeatureNotFound Error

### ISSUE THREAD

**Issue by redplant0** [alirezamika/autoscraper#2]
Tried using AutoScraper in the Python shell and I got this error.

![image](https://user-images.githubusercontent.com/29766234/92210870-1749cc80-eec2-11ea-9253-7f52ef23c6da.png)

**Comment by alirezamika** [comment]
run `pip install lxml`
should be added to requirements.

**Comment by redplant0** [comment]
> run `pip install lxml`
> should be added to requirements.

I just did. Was about to close the issue.
