### ISSUE TITLE
Scraper can't find requested data even though site is well-structured and consistent

### ISSUE THREAD

**Issue by cstrouse** [alirezamika/autoscraper#31]
This site is consistent and well-structured with easily located selectors but `autoscraper` struggles with scraping the data. I trained it with a few examples which found the data successfully but subsequent attempts to scrape other pages yields missing data even though the markup is the same for these pages as the training pages.
```python
from autoscraper import AutoScraper
scraper = AutoScraper()
scraper.build("https://www.weedsta.com/strains/blue-dream", ["Blue Dream", "Hybrid", "24.49%", "0.19%", "10 Reviews"], update=True)
scraper.build("https://www.weedsta.com/strains/trainwreck", ["Trainwreck", "Sativa", "18.63%", "0.53%", "3 Reviews"], update=True)
scraper.build("https://www.weedsta.com/strains/sour-diesel", ["Sour Diesel", "Sativa", "22.2%", "0.31%", "8 Reviews"], update=True)
```

Here's an example where you can see that the percentages are not returned.
```python
>>> scraper.get_result_similar('https://www.weedsta.com/strains/banana-kush', grouped=True)
{'rule_dt56': ['Banana Kush'], 'rule_l8fu': ['Banana Kush'], 'rule_7m0b': [], 'rule_fq5s': ['1 Reviews'], 'rule_4lqv': [], 'rule_bq2d': [], 'rule_mgmx': [], 'rule_pshq': [], 'rule_cnvq': ['Banana Kush'], 'rule_bmx8': ['Banana Kush'], 'rule_3npf': [], 'rule_7ko7': [], 'rule_tfnf': [], 'rule_ia0h': []}
>>> 
```

**Comment by alirezamika** [comment]
The reason is that the website uses different style tag values in different pages.
Adding an option to ignore styling may be good.

**Comment by linyizone** [comment]
Hi, I can't get price from this url, even though I try to add request header to it.

url: [https://www.lazada.com.my/products/pensonic-pb-7511-multifunctional-hand-blender-white-i15717885-s19365971.html](url)

```
url = "https://www.lazada.com.my/products/pensonic-pb-7511-multifunctional-hand-blender-white-i15717885-s19365971.html"
wanted_list = ["105.24"] #the price is 105.24
s = requests.session()
scraper = AutoScraper()
s.get(url, headers=scraper.request_headers)
result = scraper.build(url, wanted_list, request_args={'cookies': s.cookies.get_dict()})
```

and the output is always `None`
How can I get the price?

**Comment by alirezamika** [comment]
A new feature has been added to the new version (v1.1.7) which you can use as a workaround for this problem:
```python
scraper.get_result_similar('https://www.weedsta.com/strains/banana-kush', attr_fuzz_ratio=0.8)
```

**Comment by cstrouse** [comment]
@alirezamika Works great. Thanks a bunch!
