### ISSUE TITLE
Need help to get price from the web site.

### ISSUE THREAD

**Issue by linyizone** [alirezamika/autoscraper#33]
Hi, I can't get price from this url, even though I try to add request header to it.

url: [](https://www.lazada.com.my/products/pensonic-pb-7511-multifunctional-hand-blender-white-i15717885-s19365971.html)

```
url = "https://www.lazada.com.my/products/pensonic-pb-7511-multifunctional-hand-blender-white-i15717885-s19365971.html"
wanted_list = ["105.24"] #the price is 105.24
s = requests.session()
scraper = AutoScraper()
s.get(url, headers=scraper.request_headers)
result = scraper.build(url, wanted_list, request_args={'cookies': s.cookies.get_dict()})
```
and the output is always `None`
How can I get the price?

**Comment by alirezamika** [comment]
Hi, 

This website uses javascript to populate the data. You can get the js rendered website html content (using tools like puppeteer or Requests-HTML) and pass the html content to the scraper via html parameter.

**Comment by linyizone** [comment]
> Hi,
> 
> This website uses javascript to populate the data. You can get the js rendered website html content (using tools like puppeteer or Requests-HTML) and pass the html content to the scraper via html parameter.

thx~
