### ISSUE TITLE
Training text with extra spaces before and after while predicted text does not

### ISSUE THREAD

**Issue by predoctech** [alirezamika/autoscraper#34]
I am dealing with Q&A pages that some paragraphs contains extra spaces before and after the span (on inspecting the source), while some other span do not.  E.g.:
(With extra space) https://www.sfc.hk/en/faqs/intermediaries/licensing/Associated-entities#0FCC1339F7B94DF69DD1DF73DB5F7DCA
(No extra space) https://www.sfc.hk/en/faqs/intermediaries/licensing/Family-Offices#F919B6DCE05349D8A9E8CEE8CA9C7750

As a result it seems like a model trained with the prior would not predict latter as similar.  In fact even during the "build" process question with extra space don't treat other without space as similar.

Another question is on the expanded part of the text (the "A: " answer text).  It doesn't expand unless a "+" sign is clicked.  In that case is there anyway to get Exact result including the answer part?

Thanks for the great work.

**Comment by alirezamika** [comment]
> As a result it seems like a model trained with the prior would not predict latter as similar. In fact even during the "build" process question with extra space don't treat other without space as similar.

The problem is not spaces. Please use the latest version (v1.1.8) which will work for this issue. You may need to use `contain_sibling_leaves` when getting similar results for questions. The structure of elements in those two urls are a bit different, so you should train the model on both of them.



> Another question is on the expanded part of the text (the "A: " answer text). It doesn't expand unless a "+" sign is clicked. In that case is there anyway to get Exact result including the answer part?

The text is present in the html data so there is no need for it to be expanded. You can fetch them without expanding.

**Comment by predoctech** [comment]
Thanks for the update @alirezamika .
I tested with v1.1.8 and now building of model seems to work with that site.  However if I try to build the model using question-answer pair (the URL pages as you can tell consist of FAQ) the prediction only return answer text on other pages.  The model works with only question data (ie built with question, prediction returns question text) or answer data only, but not with question-answer pair with is what the pages are about.
Any suggestions why that would be the case, or the way model should be built or used?

**Comment by alirezamika** [comment]
@predoctech  As I told the structure of elements are different in those pages, so you should train the model on both of them:
```python
from autoscraper import AutoScraper


url1 = 'https://www.sfc.hk/en/faqs/intermediaries/licensing/Associated-entities'
url2 = 'https://www.sfc.hk/en/faqs/intermediaries/licensing/Family-Offices'


wanted_dict1 = {
    'question': ['Under s.165 (3) of the Securities and Futures Ordinance, an associated entity of an intermediary, other than an authorized financial institution, cannot conduct any business other than that of receiving or holding client assets, whether on behalf of an intermediary or otherwise, unless authorized in writing by the SFC. If an associated entity is also a licensed corporation, does it require a written authorization from the SFC?'],
    'answer': ['If the licensed corporation concerned notifies the SFC that it has become an associated entity of another intermediary, there is no need to seek additional authorisation under s.165 (3). It may continue to carry out its regulated activity(ies) as a licensed corporation.']
}

wanted_dict2 = {
    'question': ['Is there a definition for “family” or “family office” under the licensing regime?'],
    'answer': ['No, the Ordinance does not define “family” or “family office”.  It is noteworthy that the licensing regime does not hinge on whether an entity is called a family office or whether its clients are families.  A family office operator will have more flexibility to determine its legal form and operational structure with respect to its services to be provided.']
}

scraper = AutoScraper()
scraper.build(url1, wanted_dict=wanted_dict1)
scraper.build(url2, wanted_dict=wanted_dict2, update=True)
```

Now you can get result of any page with:
```python
scraper.get_result_similar(url, contain_sibling_leaves=True, group_by_alias=True)
```

**Comment by predoctech** [comment]
OK @alirezamika to be specific I was dealing with different pages for training and prediction when run into issue:
train: https://www.sfc.hk/en/faqs/intermediaries/licensing/Insurance-requirements-applicable-to-certain-licensed-corporations
predict: https://www.sfc.hk/en/faqs/intermediaries/licensing/Credit-rating-agencies

But I understand your approach now so will try with your code to see if it works on all pages.  Thanks.

**Comment by alirezamika** [comment]
One workaround for this issue is to use `text_fuzz_ratio` parameter when calling the build method and setting it lower like `0.8`. Then getting the grouped results and keep only those which contain the desired full text of the elements.
