### ISSUE TITLE
ERROR: Package 'autoscraper' requires a different Python: 2.7.16 not in '>=3.6'

### ISSUE THREAD

**Issue by mechengineermike** [alirezamika/autoscraper#35]
All 3 listed installation methods return the error shown in the issue title & cause an installation failure. No change when using pip or pip3 command.
I tried running the following 2 commands to get around the pre-commit issue but with no change in the result:
$ pip uninstall pre-commit  # uninstall from Python2.7
$ pip3 install pre-commit # install with Python3

**Comment by alirezamika** [comment]
Can you send your terminal output after running `pip3 install autoscraper` ?

**Comment by mechengineermike** [comment]
pi@raspberrypi:~ $ sudo pip3 install autoscraper
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement autoscraper (from versions: none)
ERROR: No matching distribution found for autoscraper
pi@raspberrypi:~ $ python3 --version
Python 3.7.3
pi@raspberrypi:~ $ pip3 --version
pip 20.2.4 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

**Comment by alirezamika** [comment]
Your pip3 is using python2, try:
```
python3 -m pip install autoscraper
```

**Comment by mechengineermike** [comment]
Success, thanks!
