### ISSUE TITLE
Extracting webpages with a collections of items (structurally)

### ISSUE THREAD

**Issue by ws1088** [alirezamika/autoscraper#39]
Hi,
How do I extract a list of a list of text from a webpage with:

```
Name: Amy, Age: 13
Name: Bobby, Age: 33
Name: Chris, Age: 54
```
Ideally I would like the results to be:
```
[['Amy', '13'],
 ['Bobby', '33],
 ['Chris', '54']
]
```

**Comment by alirezamika** [comment]
Hey! Can you share your webpage?

**Comment by ZiggerZZ** [comment]
Hi!

I'm interested in the same thing.
An example: scrape item names and prices from https://www.ubereats.com/london/food-delivery/mcdonalds-balham-high-road/DJEVCmFOTpy3vR-CB7RCDA .

P.S. Actually, I'd only need to scrape items that are _Sold out_, but I guess it can be a second challenge.

**Comment by alirezamika** [comment]
Hi, 
use wanted_dict with aliases, then get the results grouped by rule and fine tune the rules. then you can use goup_by_alias results as you want.

**Comment by rooterkyberian** [comment]
It would be good to have example for this in docs since it seems like a common use case.

Is it possible for `autoscraper` to "scrape"
```
<div>Name: Amy, Age: 13</div>
<div>Name: Bobby,</div>
<div>Name: Chris, Age: 54</div>
```
as well? i.e. group data entries when we have different number of instances for particular field
