### ISSUE TITLE
HTML Parameter

### ISSUE THREAD

**Issue by j3vr0n** [alirezamika/autoscraper#42]
I read a previous post that mentioned capability for the HTML parameter, in which I could render a JS application using another tool (BS or Selenium) and pass in the HTML data for AutoScraper to parse. Does anyone have steps or documentation on how to use this parameter?

**Comment by Vulcan-Coder** [comment]
> I read a previous post that mentioned capability for the HTML parameter, in which I could render a JS application using another tool (BS or Selenium) and pass in the HTML data for AutoScraper to parse. Does anyone have steps or documentation on how to use this parameter?

In the first example it says you can parse the html instead of the URL. 
https://github.com/alirezamika/autoscraper#getting-exact-result

Just do a request with selenium etc, and return the html. Then put it in there.

**Comment by j3vr0n** [comment]
Awesome, I have a third party scraping tool that I actively use and am looking to embed this Python code as part of my jobs in order to have better "self-healing" measures for website changes from the HTML.
