### ISSUE TITLE
Add support for sepecifying text encoding.

### ISSUE THREAD

**Issue by RealXuChe** [alirezamika/autoscraper#44]
I'm working with a legacy Chinese site with BIG5 text encoding, and I'm not able to set text encoding by passing arguments through `request_args`, because requests don't support it. 

So the results I get was garbled, like this: `'¡ ̧ÔÚÕâ ̧öÊÀ1⁄2ç ̧æÖÕÒÔÇ°©¤©¤A¡1-promise/result-'`.

Encoding can only be set by writing to the `encoding` property of requests object (According to [this](https://requests.readthedocs.io/en/master/user/quickstart/#response-content)). 

So maybe adding an `encoding` param and set encoding in `_get_soup` in `auto_scraper.py` would be a good idea.

**Comment by alirezamika** [comment]
Yeah thanks. 
for now you can pass the html content via `html` parameter.

**Comment by RealXuChe** [comment]
Here's the website:
https://www.wenku8.net/novel/2/2231/index.htm
And, I've made a mistake, the encoding of this site is GB2312.

**Comment by alirezamika** [comment]
Should be fixed now. (v1.1.12)
