### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by programmeddeath1** [alirezamika/autoscraper#47]
Hi how can I handle pagination for example if I want to fetch comments and reviews.
And is there a way to detect/handle consecutive pages other than by listing them like how general scrapers would have a click function to move to different pages or actions.

**Comment by Vulcan-Coder** [comment]
There are two ways you can do it. If the site has a next button, you can scrape the button and see if it is active, if it's active you add one to the page number in the URL and carry on scrapping.

Two is you do an Initial scrape to get the total number of pages. Then do a range loop using  the number of pages to scrape each page.
