### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by regisbaillieul** [alirezamika/autoscraper#51]
Hi, when i launch  : python3 autoscraper.py,
i got the following error:
ImportError: cannot import name 'AutoScraper' from partially initialized module 'autoscraper' (most likely due to a circular import)

Have you any idea of the fix?
Thanks for your reply.

Regards

**Comment by alirezamika** [comment]
Hi, try changing your file name from `autoscraper.py` to another name.

**Comment by silverxd20** [comment]
Thank that 

> Hi, try changing your file name from `autoscraper.py` to another name.

Thank you, that solve the problem.
