### ISSUE TITLE
how to use this behind a proxy

### ISSUE THREAD

**Issue by mikelty** [alirezamika/autoscraper#52]
this is a great project but when i open a proxy, nothing worked. help please.

**Comment by alirezamika** [comment]
can you use the requests module with your proxy?

**Comment by mikelty** [comment]
yeah, with a proxies variable in requests like such:

https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module

(sorry for the late response)

**Comment by alfarias** [comment]
@mikelty Do you have solved your problem using proxies? I got some problems when using a proxy, but it was a bug on requests module, I don't know if you got a similar problem.

**Comment by alirezamika** [comment]
@mikelty is your problem solved?
