### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by petrsevcik** [alirezamika/autoscraper#57]
I have a problem with importing AutoScraper(). Not sure where can be a problem. All description here: https://stackoverflow.com/questions/66551742/autoscraper-module-not-found-in-python-autoscraper-library 

Thanks for help

**Comment by alirezamika** [comment]
try changing your file name from autoscraper.py to something else.

**Comment by petrsevcik** [comment]
Okay, now it is working. Stupid mistake, but good to know. I am still a beginner in coding. Looking forward to try your module.
