### ISSUE TITLE
Is there a way to scrape information from multiple pages?

### ISSUE THREAD

**Issue by siddharthchauhan** [alirezamika/autoscraper#59]
I want to scrape information from all the pages of a website, Is there a way that it will go to next page automatically and scrape it?

**Comment by Vulcan-Coder** [comment]
Are you trying to scrape all the site or just scrape the next page until there is no next page?

**Comment by siddharthchauhan** [comment]
Next page until there is no page.

**Comment by Vulcan-Coder** [comment]
Writing a recursive function should handle that. 

When you scrape, also get the next button, if it's active you call the same function using the link of the button.

**Comment by siddharthchauhan** [comment]
Can you please write the psudo code or something how will I fetch URL for the next page.

**Comment by siddharthchauhan** [comment]
The  page i want to scrape has no next button it has symbol '>'.

**Comment by siddharthchauhan** [comment]
The website has this kind of structure 
< 1, 2, 3 ,4, 5 >

**Comment by Vulcan-Coder** [comment]
The one you are currently on should look different to the rest.
