### ISSUE TITLE
Scraping skips item

### ISSUE THREAD

**Issue by zepef** [alirezamika/autoscraper#60]
Hello,

I am really delighted with this fantastic module. However I want to signal a lillte annoying bug:
1. I am trying to scrape wsj.com.
2. In the wanted list I put the left column 1st article title and left colum 1st article summary.
3. The results list does not include the head (up center) article summary but it includes its title.
4. Number of list elements is 33 where it should be 34 (17 titles + 17 summaries).

I do suspect that since the head summary is align/centered and the other artcile summaries are align/left this might cause this skipping.

Thank You indeed, all te best

Pierre-Emmanuel FEGA

**Comment by alirezamika** [comment]
Hi, if you still have this issue please reopen an issue providing your code. thanks.
