### ISSUE TITLE
scraper.build returns a blank list

### ISSUE THREAD

**Issue by p595285902** [alirezamika/autoscraper#64]
Here is the code to reproduce:

        
        from autoscraper import AutoScraper
        
        class Scraper():
            
            wanted_list = ["0.79"]
            origUrl = 'https://www.sec.gov/Archives/edgar/data/0001744489/000174448921000105/fy2021_q2xprxex991.htm'
            newUrl = 'https://www.sec.gov/Archives/edgar/data/0001744489/000174448921000179/fy2021_q3xprxex991.htm'
            path="Alpaca/Scraper/sec/file.txt"
            
            def scrape(self):
                scraper = AutoScraper()
                result = scraper.build(self.origUrl, self.wanted_list)
                print(result)
                result = scraper.get_result_exact(self.newUrl)
                print(result)
        
        if __name__ == '__main__':
            scraper = Scraper()
            scraper.scrape()

Here is the log:

        []
        []

Expected to be:

        [0.79]
        [0.80]

**Comment by alirezamika** [comment]
This website is using bot detection methods, maybe u can load it with selenium and pass the html to the scraper.
