### ISSUE TITLE
Trying to scrap email address from any given website.

### ISSUE THREAD

**Issue by gpnaveen** [alirezamika/autoscraper#65]
Trying to scrap email address from any given website.

It returns empty list.

How it can be used to scrap all the email gives on website.

**Comment by alirezamika** [comment]
what's the code you are using?

**Comment by gpnaveen** [comment]
```
from autoscraper import AutoScraper

url = 'https://stackoverflow.com/questions/2081586/web-scraping-with-python'

# We can add one or multiple candidates here.
# You can also put urls here to retrieve urls.
wanted_list = ["@"]

scraper = AutoScraper()
result = scraper.build(url, wanted_list)
print(result)
```

**Comment by alirezamika** [comment]
no need to use this package for this usecase. just use a regex to find emails in the html content.

**Comment by lorey** [comment]
Here's the regex: https://github.com/lorey/social-media-profiles-regexs#email
