### ISSUE TITLE
How to scrape a dynamic website?

### ISSUE THREAD

**Issue by vChavezB** [alirezamika/autoscraper#71]
I am trying to export a localhost website that is generated with this project:

https://github.com/HBehrens/puncover

The project generates a localhost website, and each time the user interacts clicks a link the project receives a GET request and the website generates the HTML. This means that the HTML is generated each time the user access a link through their browser. At the moment the project does not export the website to html or pdf. For this reason I want to know how could I recursively get all the hyperlinks and then generate the HTML version. Would this be possible with autoscraper?

**Comment by lrq3000** [comment]
You can supply a `html` argument to `scraper.build()` to use the output of your preferred HTML fetcher.
