### ISSUE TITLE
Not able to scrape images from amazon and flipkart from product pages

### ISSUE THREAD

**Issue by swaroopvemula** [alirezamika/autoscraper#72]

**Comment by notChewy1324** [comment]
this scrapes text from websites

**Comment by anoduck** [comment]
> this scrapes text from websites

It was able to scrape image links, but not the images themselves. Greatly disappointed.

**Comment by anoduck** [comment]
> 

Allow me to clarify, in my script "image_link" is not the direct URL to the image, but a linked image that resolved to the image hosting service which hosted the image. Such as imagetwist. 

The library was able to retrieve the first link leading to the image hosting service, but was not able to retrieve the direct url to the image on that hosting service.

**Comment by anoduck** [comment]
Yeah, the issue needed closing.
