### ISSUE TITLE
Scrapping output is zero 

### ISSUE THREAD

**Issue by sbhadade** [alirezamika/autoscraper#76]
i tried to scrape the webpage but the results are zero 👍 

/////////
`
from autoscraper import AutoScraper

url = 'https://trade.mango.markets/account?pubkey=8zJHqNa9sVvyLmVBQwY2vch5729dqfmzF3cxE25ZYVn'

wanted_list = ['Futures Positions','Notion Size']

scraper = AutoScraper()
result = scraper.build(url, wanted_list)
print(result)

`
/////

Output Results are none

@alirezamika can you guide whats the issue:
1.  are the webpage is using node.js ?

**Comment by alirezamika** [comment]
this website use js to fetch data.

**Comment by sbhadade** [comment]
Guide me sir how to proceed with the above url
