### ISSUE TITLE
Package couldn't be installed

### ISSUE THREAD

**Issue by SoumyadeepOSD** [alirezamika/autoscraper#79]
<b>Tried out different ways to install it, but failed every time</b>

![bs4](https://user-images.githubusercontent.com/115442240/205690298-e97c770a-f00e-4d27-a9da-758905ea41d6.png)

<b>how can I install this package successfully?Can anyone tell me?</b>

**Comment by lorey** [comment]
https://idownvotedbecau.se/imageofanexception/
https://idownvotedbecau.se/nomcve/
https://idownvotedbecau.se/noresearch/

**Comment by alirezamika** [comment]
https://stackoverflow.com/questions/33785755/getting-could-not-find-function-xmlcheckversion-in-library-libxml2-is-libxml2
