### ISSUE TITLE
Ignores duplicate value

### ISSUE THREAD

**Issue by thouravi** [alirezamika/autoscraper#83]
Hi,

I was trying to fetch from a website which had some duplicate values like item A and item B had similar price i.e. $1.0
Your AutoScraper simply ignored any duplicate values and fetched unique items to the result list.

Website had 18 items, result list had only 5, all unique.
I hope if you can fix this issue, thanks.

**Comment by alirezamika** [comment]
You can use `unique=False` parameter.

**Comment by thouravi** [comment]
This is my code:

```
from autoscraper import AutoScraper

url = 'https://csgostash.com/stickers/tournament/Rio+2022?name=&sticker_type=tournament_team&rarity_contraband=0&rarity_covert=0&rarity_legendary=0&rarity_mythical=0&rarity_rare=1&container=any&sort_agg=avg&sort=default'

wanted_list = ["$0.16"]
scraper = AutoScraper()
result = scraper.build(url, wanted_list)
```

Where can I add this parameter?

**Comment by alirezamika** [comment]
You can use this parameter with `get_result_similar` function.

**Comment by thouravi** [comment]
The thing is when I use `get_result_similar` it only gives one output out of 18 on the website. 
I tried it, no success.

**Comment by thouravi** [comment]
It worked, thanks. I wish it was a default property.
