### ISSUE TITLE
autoscraper for amazon not working

### ISSUE THREAD

**Issue by alice23DS** [alirezamika/autoscraper#87]
I am trying to scrape data from amazon through autoscraper but it is fetching empty list

![image](https://user-images.githubusercontent.com/123429653/228414909-75ae7ff7-4f01-4083-b3eb-1d57b5b1b090.png)

**Comment by SaadTazroute** [comment]
the link should be specific to the product page (it should contains the text you put in wanted_list)

**Comment by dikshant182004** [comment]
i have the same issue
