### ISSUE TITLE
Scrape local html files

### ISSUE THREAD

**Issue by csimlinger** [alirezamika/autoscraper#97]
Hi,

is there any way I can scrape locally hosted URLs?
Alternatively, can I somehow directly paste html code to the tool?

Thanks!

**Comment by alirezamika** [comment]
> is there any way I can scrape locally hosted URLs?
yes just use the localhost url.

> Alternatively, can I somehow directly paste html code to the tool?
yes you can use the `html` attribute instead of the `url`.
